Simplify gpg-agent functions in home/.bash/gpg-agent

diff --git a/home/.bash/gpg-agent b/home/.bash/gpg-agent
--- a/home/.bash/gpg-agent
+++ b/home/.bash/gpg-agent
@@ -24,44 +24,15 @@
 #  along with dot-files. If not, see <http://www.gnu.org/licenses/>.
 #
 
-#  Set gpg agent information
-export GPG_AGENT_INFO
-
 #  Set gpg tty
 export GPG_TTY="$(tty)"
 
-#  List active gpg agents
-gpg-agent-list() {
-	ps -x "$@" | grep "[g]pg-agent"
-}
-
-#  Initialize a gpg agent if no gpg agents are active
+#  Initialize gpg-agent if it is not already active
 gpg-agent() {
-	if gpg-agent-list &> /dev/null; then
-		>&2 echo "gpg-agent: error: One or more gpg agents are already active"
-		return 1
+	if [[ -z "${GPG_AGENT_INFO}" ]]; then
+		command gpg-agent --daemon "${SHELL}"
 	else
-		command gpg-agent --verbose --write-env-file "$HOME/.gpg-agent-info" "$@"
-		gpg-agent-info-update
-	fi
-}
-
-#  Update gpg agent information
-gpg-agent-info-update() {
-	if [[ -f "$HOME/.gpg-agent-info" ]]; then
-		source "$HOME/.gpg-agent-info"
-	fi
-}
-
-#  Kill active gpg agents
-gpg-agent-kill() {
-	if gpg-agent-list &> /dev/null; then
-		kill $(gpg-agent-list | cut -c 1-5) 
-	else
-		>&2 echo "gpg-agent: error: No gpg agents are active"
+		>&2 echo "gpg-agent: error: gpg-agent is already active"
 		return 1
 	fi
 }
-
-#  Update gpg agent information
-gpg-agent-info-update
