Update gpg-agent error message in home/.bash/gpg-agent

diff --git a/home/.bash/gpg-agent b/home/.bash/gpg-agent
--- a/home/.bash/gpg-agent
+++ b/home/.bash/gpg-agent
@@ -32,7 +32,7 @@ gpg-agent() {
 	if [[ -z "${GPG_AGENT_INFO}" ]]; then
 		command gpg-agent --daemon "${SHELL}"
 	else
-		>&2 echo "gpg-agent: error: gpg-agent is already active"
+		echo "gpg-agent: error: gpg-agent is already active" >&2
 		return 1
 	fi
 }
